### ISSUE TITLE
Difference between PIN and OTP

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [Flutterwave/Flutterwave-node-v3#10]
if (response.meta.authorization.mode === 'pin') {
            let payload2 = payload
            payload2.authorization = {
                "mode": "pin",
                "fields": [
                    "pin"
                ],
                "pin": 3310
            }
            const reCallCharge = await flw.Charge.card(payload2)

            const callValidate = await flw.Charge.validate({
                "otp": "12345",
                "flw_ref": reCallCharge.data.flw_ref
            })
            console.log(callValidate)

        }

just a quick question, am i getting both the "pin" and "otp" value from the user ?

**Comment by alob-mtc** [comment]
Yes, the PIN and OTP are both gotten from the user.

**Comment by GoodnessEzeokafor** [comment]
usually banks just sends otp, banks don't send both and in the docs it looks like the aren't the same thing

**Comment by Olufemiobafunmiso** [comment]
Hi @GoodnessEzeokafor 

The card issuer (Bank) sends the `OTP`

The User Provides `PIN`
