### ISSUE TITLE
Mobile money franco unknown error

### ISSUE THREAD

**Issue by drosarl** [Flutterwave/Flutterwave-node-v3#16]
I am tying a simple request from node js but I keep getting this error

{ status: 'error', message: 'Transaction Failed', data: null }

It works with the message payment initiated. so I want to try it on live and see how it interact with phone. Is there any missing data?

import Ravepay from "flutterwave-node-v3";
import { v4 } from "uuid";

const flw = new Ravepay(
	"MY_PUBLIC_KEY",
	"MY_SECRET_KEY",
	true,
);

const pay = async (_request, response) => {
	try {
		const payload = {
			tx_ref: v4(),
			amount: "500",
			currency: "XOF",
			email: "olufemi@flw.com",
			phone_number: "08517414",
			firstname: "temi",
			name: "frediustcdev is here",
			fullname: "dro freddy",
			lastname: "desola",
			is_mobile_money_franco: 1,
			country: "CI",
		};

		const result = await flw.MobileMoney.franco_phone(payload);

		console.log("[success] => ", result);

		response.status(200).send(result.data);
	} catch (error) {
		console.log("[ERROR] => ", error);

		response.status(400).send(error);
	}
};

**Comment by MohammedBashiru** [comment]
Instead of waiting for an answer you can extend the API your self. 
Since this is just a wrapper for their http-api

**Comment by Corvus97** [comment]
Hello @drosarl,

Please note that the params `is_mobile_money_franco` has been deprecated in v3 (as it is a v2 parameter).

Kindly make use of the payload structure below for francophone mobile money charge:

```{
   "tx_ref":"MC-158523s09v5050e8",
   "amount":"1500",
   "currency":"XAF",
   "email":"user@flw.com",
   "phone_number":"054709929220",
   "fullname":"John Madakin"
}```

Regards,
Cornelius
