### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by drosarl** [Flutterwave/Flutterwave-node-v3#17]
I would like to know if there is any way for us to contribute to the library even by testing. We are base in Ivory Coast. It will be great if we can work on the implementation  of the payments located here.

**Comment by Corvus97** [comment]
Hello @drosarl,

Thank you for reaching out.

Please be advised that all payments can be mock in our test environment.

Kindly refer to our docs on payments here - https://developer.flutterwave.com/reference

Regards,
Cornelius
