### ISSUE TITLE
Frontend Implementation?

### ISSUE THREAD

**Issue by Aromokeye** [Flutterwave/Flutterwave-node-v3#19]
How should the json data be collected from the front-end?

**Comment by its-tayo** [comment]
What JSON data? It will help if you're a bit more specific.

**Comment by Corvus97** [comment]
Hello @Aromokeye,

Please share more details regarding the issue on our forum(https://developer.flutterwave.com/discuss) for quicker resolution.

Best regards,
Cornelius
