### ISSUE TITLE
Error: Cannot find module 'flutterwave_node_3

### ISSUE THREAD

**Issue by AbdulRazak-Naeate** [Flutterwave/Flutterwave-node-v3#24]
Please I need assistance in implementing the package, I get  "Error: Cannot find module 'flutterwave_node_3'" when I required it, I use Browserify. Is there a way I should go about this or what am I not doing right?

**Comment by Olufemiobafunmiso** [comment]
Hi @AbdulRazak-Naeate 

The Package name is `flutterwave-node-v3` not `flutterwave_node_3`. 

There's no underscore(_).

Steps to require the Package:
- npm i flutterwave-node-v3
- const Flutterwave = require('flutterwave-node-v3');

Kindly check the docs [here](https://github.com/Flutterwave/Flutterwave-node-v3#readme)

**Comment by the-timoye** [comment]
I have this error too. With the right naming 'flutterwave-node-v3'. 
I tried to declare the module in the tsconfig file, but it still brought some other errors like:


Unable to resolve module `path` from `...node_modules/flutterwave-node-v3/services/beneficiaries/rave.single.retrieve.js`: Module `path` does not exist in the Haste module map.

Please can you help with this?
