### ISSUE TITLE
get_fee returning 10x transaction fee in response

### ISSUE THREAD

**Issue by DavidQuartz** [Flutterwave/Flutterwave-node-v3#31]
The function for calculating transaction fees is returning an amount over 10 times higher than what the transaction fee should be. This just started happening. It wasn't so just yesterday.

Here is an example of the fee on a trial amount of GHS 100.94:

data: {
    charge_amount: 100.94,
    fee: 28.87,
    merchant_fee: 0,
    flutterwave_fee: 28.87,
    stamp_duty_fee: 0,
    currency: 'GHS'
  }

The fee should originally be GHS 2.53 (using the rate of 2.5%)  but is instead showing GHS 28.87. Please fix.

**Comment by ugwumadu116** [comment]
this issue has been resolved
