### ISSUE TITLE
Verify transaction

### ISSUE THREAD

**Issue by Khabz** [Flutterwave/Flutterwave-node-v3#32]
Cannot verify or get transaction using reference tx_ref. Only alternative is verifying or getting transaction by id

**Comment by Corvus97** [comment]
Hello @Khabz, 

This is because, in the v3 version of our F4B APIs, transactions can only be verified by their transaction IDs.

You can check out more details (here)[https://developer.flutterwave.com/reference#verify-transaction] about verifying transactions in v3.

**Comment by umohpyro** [comment]
Hello @corneliusyaovi 

I can confirm this issue still persists. I get the following response when I try to verify a transaction with either trx_ref or transaction ID using the following endpoints I found in the verify transaction docs.

`{
    "status": "error",
    "message": "No transaction was found for this id",
    "data": null
}`

I have tried the following endpoints:

1. `https://api.flutterwave.com/v3/transactions/:id/verify `
2. `https://api.flutterwave.com/v3/transactions/verify_by_reference/?tx_ref=:tx_ref`

Could you please confirm what I need to do to solve this issue?

Thank you.
