### ISSUE TITLE
Old axios depedency

### ISSUE THREAD

**Issue by gal1l0** [Flutterwave/Flutterwave-node-v3#39]
### The issue
`Flutterwave-node-v3` is dependent on the axios `0.19.x` which is vurnelable to Serverside request forgery attacks
unfortunately there's no fix avaiable with snyk or npm audit the result is my code holds 2 high severity vulnerabilities

### Expected behaviour
The package should be depending on updated versions of axios
### Supporting docs
 The npm advisory on this can be found [here](https://npmjs.com/advisories/1594)

**Comment by bodolawale** [comment]
Please fix this.

**Comment by Corvus97** [comment]
@gal1l0 @bodolawale Thanks for bringing this up with the team.

This has been fixed.
