### ISSUE TITLE
Transaction fails on entering otp

### ISSUE THREAD

**Issue by drexhacker** [Flutterwave/Flutterwave-node-v3#42]
Flutterwave mobilemoneyug fails after OTP it says `An Error occured` And after inspecting the response code is 400(Bad Request)

**Comment by Corvus97** [comment]
This is an API error. Please send us the details of the transaction attempt via [mail](mailto:developers@flutterwavego.com)

**Comment by drexhacker** [comment]
Actually, it is solved. Thank You!
