### ISSUE TITLE
i can't find virtual card update api

### ISSUE THREAD

**Issue by lecuong9k** [Flutterwave/Flutterwave-node-v3#49]
i have problem, i want to update my virtual card on flutterware to be able to know the balance of the card. But what api do I find now :( can you help me find that api?

**Comment by Corvus97** [comment]
Hello @lecuong9k,

Thanks for sharing your experience with us.

This however is not an issue from the library. Kindly share this with the team via email at [developers@fluterwavego.com](mailto:developers@fluterwavego.com). We would be on the lookout for your email😊.

We would close out this issue. If you have any additional questions, you can send them via mail or create a question on our [Forum](https://forum.flutterwave.com/).

Kind regards,
