### ISSUE TITLE
AUTHORIZATION

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [Flutterwave/Flutterwave-node-v3#5]
How do i redirect user to put in their pin ??
sorry your little documentation is not really clear abeg

**Comment by Olufemiobafunmiso** [comment]
Hi @GoodnessEzeokafor
To achieve this, kindly check below;
`if (response.meta.authorization.mode === 'pin')` 

if this is true, you can render a page to collect Users PIN and add the following to the initial payload.

```javascript
authorization = {
                "mode": "pin",
                "fields": [
                    "pin"
                ],
                "pin": 3310 // Users PIN
            }
```
Then call charge again with the added params to the payload

`const reCallCharge = await flw.Charge.card(payload2)`

Then you can proceed to validate  by calling validate.
```javascript
const callValidate = await flw.Charge.validate({
                "otp": "12345" //Users OTP,
                "flw_ref": reCallCharge.data.flw_ref
            })
```
Kindy check [here](https://medium.com/@jake_parkers/ultimate-guide-to-card-transactions-with-rave-420e7290f8b9) to see how card transaction works.

Once again, thank you for the documentation feedback.

The team will review it

**Comment by GoodnessEzeokafor** [comment]
Thanks
would also love to know when is you guys flutterwave expert programme
