### ISSUE TITLE
Question: Difference between "amount" & "charged_amount" in Webhook response

### ISSUE THREAD

**Issue by holymp2006** [Flutterwave/Flutterwave-node-v3#54]
It seems already clear in the naming, but I want to make sure, as I couldn't find where it's stated in the docs. 
What's the difference between the "amount" and  "charged_amount" keys in the webhook response?

**Comment by Corvus97** [comment]
Hello @holymp2006,

There is a subtle difference in the amount and charged_amount depending on who is bearing the transaction fees. In the case where the merchant bears the fees, charged_amount = amount

When the customer bears the fees,  charged_amount = amount + fees

I hope this explains better the two params. Let me know if you have any other questions.

**Comment by holymp2006** [comment]
Thanks @Corvus97, you've cleared my confusion.
