### ISSUE TITLE
Typo error in Readme

### ISSUE THREAD

**Issue by Daemonicc** [Flutterwave/Flutterwave-node-v3#55]
in the bulk transfer sample "account_numberr" was used instead of "account_number"

**Comment by Corvus97** [comment]
Hello @Daemonicc 👋🏽,

Thank you for catching that. The typo has been corrected and the full ReadMe is undergoing an extensive review.

We would notify you and other members of our community as soon as this review is completed.

Please let us know how else we can improve your experience with the SDK.

You can join our [Slack channel](https://bit.ly/34Vkzcg) for more updates from the Engineering team.
