### ISSUE TITLE
Does this support creating payment links

### ISSUE THREAD

**Issue by MohammedBashiru** [Flutterwave/Flutterwave-node-v3#6]
Hi I can't seem to find the API to generate payment link using this SDK.
Does this support payment links yet ?

reference
https://api.flutterwave.com/v3/payments
https://developer.flutterwave.com/docs/flutterwave-standard

**Comment by Olufemiobafunmiso** [comment]
Hi @MohammedBashiru 

The feature to generate payment links is currently not on the SDK.

Thank you

**Comment by MohammedBashiru** [comment]
Ok
