### ISSUE TITLE
DEPRECATED DEPENDENCIES

### ISSUE THREAD

**Issue by iamveekthorr** [Flutterwave/Flutterwave-node-v3#66]
![image](https://user-images.githubusercontent.com/38949632/161200101-51688323-c2e7-4050-8efe-0ad224cece8b.png)

to reproduce this issue: npm i flutterwave-node-v3

**Comment by Corvus97** [comment]
Hello @iamveekthorr 👋🏽,

Thanks for bringing our attention to this. The team is working on fixing all these and a new version should be rolled out this weekend.

Please let us know how else we can improve the SDK.

You can join our [slack](https://bit.ly/34Vkzcg) channel to get more updates from the Engineering team.
