### ISSUE TITLE
Payout - subaccounts

### ISSUE THREAD

**Issue by japhethkiptoo** [Flutterwave/Flutterwave-node-v3#67]
Get All Transactions 
Get Available Balance

**Comment by Corvus97** [comment]
Hello @japhethkiptoo,

Thanks for bringing our attention to this. We however need more details on the nature of the issue you are experiencing and how to replicate the issue.

Kindly share details like the error message, sample reference for the transaction attempts and steps involved in replicating the error. We would remain on standby for your feedback.
