### ISSUE TITLE
How to trigger payment.Popup from nodejs

### ISSUE THREAD

**Issue by cosmotranglobal** [Flutterwave/Flutterwave-node-v3#7]
## Feature Request
Please a trying to trigger the Rave inline popup from **nodejs**.
Please is there a way to call it from the current API.

---
### FrontEnd Frameworks
Or is there an **Angular, React, Vue**, etc framework component on npm for it?
I've tried injecting [this](https://checkout.flutterwave.com/v3.js) into the node-server but there seems to be no `export` to call the Popup
> https://stackblitz.com/edit/payvest-rave-payment-test

---

[This](https://developer.flutterwave.com/docs/flutterwave-inline) works fine on plain HTML & JS
> https://stackblitz.com/edit/payvest-ravepayment-test

**Comment by Corvus97** [comment]
Hello @cosmotranglobal, 

Kindly be informed that the Team is working on releasing the v3 APIs on Angular, Vue and React frameworks.

We'd keep you and other members of our Flutterwave community in the loop so you can be informed of all our developments.

Remain Awesome!
Cornelius.
