### ISSUE TITLE
I'm unable to make a payment using the sandbox payment link.

### ISSUE THREAD

**Issue by humanityjs** [Flutterwave/Flutterwave-node-v3#70]
I have a simple setup where I'm creating a payment link on the server using the `https://api.flutterwave.com/v3/payments` endpoint and then redirecting to the link on the frontend. 

I haven't been able to make a successful payment. The processing loader keeps spinner endlessly with some errors in the console. 

Please find attached some screenshots.

Would really appreciate some help here ASAP. Thanks.

1.
<img width="1800" alt="Screenshot 2022-04-27 at 9 42 40 AM" src="https://user-images.githubusercontent.com/22296251/165480745-5e666751-eb60-45d1-8275-f966d42aa941.png">

2.
<img width="1798" alt="Screenshot 2022-04-27 at 9 42 24 AM" src="https://user-images.githubusercontent.com/22296251/165480734-101b6266-e1da-4097-9598-501eb1ced5e5.png">

**Comment by Corvus97** [comment]
Hello @humanityjs,

Thanks for sharing your experience with us.

This however is not an issue from the library. Kindly share this with the team via email at developers@fluterwavego.com. We would be on the lookout for your email😊.

We would close out this issue. If you have any additional questions, you can send them via mail or create a question on our [Forum](https://forum.flutterwave.com/).

Kind regards,
